/**********************************************************************
            --- KDevelop (KDlgEdit)  generated file ---                

            Last generated: Mon Apr 17 09:35:11 2000

            DO NOT EDIT!!!  This file will be automatically
            regenerated by KDevelop.  All changes will be lost.

**********************************************************************/
#include <kapp.h>
#include <qpixmap.h>
#include "kenddlg.h"

void  kEndDlg::initDialog(){
  this->resize(470,150);
  this->setMinimumSize(0,0);
  QLabel_1= new QLabel(this,"NoName");
  QLabel_1->setGeometry(340,10,114,64);
  QLabel_1->setMinimumSize(0,0);
  QLabel_1->setPixmap(*mPixmap);

  QLabel_2= new QLabel(this,"NoName");
  QLabel_2->setGeometry(10,10,114,64);
  QLabel_2->setMinimumSize(0,0);
  QLabel_2->setPixmap(*mPixmap);

  QPushButton_1= new QPushButton(this,"NoName");
  QPushButton_1->setGeometry(20,100,100,30);
  QPushButton_1->setMinimumSize(0,0);
  QPushButton_1->setText(i18n("Good bye"));

  QPushButton_2= new QPushButton(this,"NoName");
  QPushButton_2->setGeometry(350,100,100,30);
  QPushButton_2->setMinimumSize(0,0);
  QPushButton_2->setText(i18n("Stay here"));

  QGroupBox_1= new QGroupBox(this,"NoName");
  QGroupBox_1->setGeometry(140,10,190,130);
  QGroupBox_1->setMinimumSize(0,0);

  QLabel_4= new QLabel(QGroupBox_1,"NoName");
  QLabel_4->setGeometry(10,90,170,30);
  QLabel_4->setMinimumSize(0,0);
  QLabel_4->setText(i18n("Sure you really wanna quit?"));

  QLabel_5= new QLabel(QGroupBox_1,"NoName");
  QLabel_5->setGeometry(30,10,130,30);
  QLabel_5->setMinimumSize(0,0);
  QLabel_5->setText(i18n("Thanks for playing !"));

  QLabel_6= new QLabel(QGroupBox_1,"NoName");
  QLabel_6->setGeometry(40,50,110,30);
  QLabel_6->setMinimumSize(0,0);
  QLabel_6->setText(i18n("Come back soon"));

}
