/**********************************************************************
            --- KDevelop (KDlgEdit)  generated file ---                

            Last generated: Sun Apr 16 18:04:10 2000

            DO NOT EDIT!!!  This file will be automatically
            regenerated by KDevelop.  All changes will be lost.

**********************************************************************/
#include <kapp.h>
#include <qpixmap.h>
#include "kwin4aboutdlg.h"

void  kwin4AboutDlg::initDialog(){
  this->resize(320,290);
  this->setMinimumSize(0,0);
  QGroupBox_1= new QGroupBox(this,"NoName");
  QGroupBox_1->setGeometry(20,10,280,230);
  QGroupBox_1->setMinimumSize(0,0);
  QGroupBox_1->setBackgroundColor(Qt::white);
  QGroupBox_1->setFrameStyle(QFrame::Panel|QFrame::Sunken);
  QGroupBox_1->setLineWidth(3);
  QGroupBox_1->setMidLineWidth(2);

  QLabel_1= new QLabel(QGroupBox_1,"NoName");
  QLabel_1->setGeometry(10,90,260,40);
  QLabel_1->setMinimumSize(0,0);
  QLabel_1->setText(i18n("Mail: martin@heni-online.de"));
  QLabel_1->setBackgroundColor(Qt::white);

  QLabel_7= new QLabel(QGroupBox_1,"NoName");
  QLabel_7->setGeometry(160,10,90,30);
  QLabel_7->setMinimumSize(0,0);
  QLabel_7->setText(i18n("Four wins"));
  QLabel_7->setBackgroundColor(Qt::white);

  QLabel_2= new QLabel(QGroupBox_1,"NoName");
  QLabel_2->setGeometry(10,10,114,64);
  QLabel_2->setMinimumSize(0,0);
  QLabel_2->setPixmap(*mPixmap);
  QLabel_2->setBackgroundColor(Qt::white);

  QLabel_8= new QLabel(QGroupBox_1,"NoName");
  QLabel_8->setGeometry(10,70,200,25);
  QLabel_8->setMinimumSize(0,0);
  QLabel_8->setText(i18n("(c) 1995-2000 by Martin Heni"));
  QLabel_8->setBackgroundColor(Qt::white);

  QLabel_5= new QLabel(QGroupBox_1,"NoName");
  QLabel_5->setGeometry(10,120,260,100);
  QLabel_5->setMinimumSize(0,0);
  QLabel_5->setText(i18n(
  "Gamefeatures:\n"
  "- Multiplayer network game\n"
  "- Computerplayer with ten levels\n"
  "\n"
  "Thanks to Laura for betatesting!\n"));
  QLabel_5->setBackgroundColor(Qt::white);

  QLabel_11= new QLabel(QGroupBox_1,"NoName");
  QLabel_11->setGeometry(160,40,100,30);
  QLabel_11->setMinimumSize(0,0);
  QLabel_11->setText(i18n("Version 0.9"));
  QLabel_11->setBackgroundColor(Qt::white);

  QPushButton_1= new QPushButton(this,"NoName");
  QPushButton_1->setGeometry(110,250,100,30);
  QPushButton_1->setMinimumSize(0,0);
  QPushButton_1->setFocus();
  QPushButton_1->setText(i18n("Ok"));

}
